version: '3.1'

services:
    api:
        build: 
            context: api/
            dockerfile: ${PWD}/api/Dockerfile
        ports: 
            - 5000:80
        restart: always
        depends_on: 
            - db

    db:
        image: mysql:latest
        hostname: db
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - 3306:3306
        environment: 
            MYSQL_USER: weather-api-user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: weather_api
        restart: always
        volumes:
            - weather-api-db:/var/lib/mysql

volumes: 
    weather-api-db:

